name: Coverage

on:
  push:
    branches:
      - '2.*'
  pull_request:
    types:
      - synchronize
      - opened
      - edited
      - reopened

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      # Configure PHP
      - name: Select PHP version
        uses: shivammathur/setup-php@master
        with:
          php-version: '7.4'
          extensions: mbstring, pdo_sqlite, fileinfo, gd
          coverage: pcov

      # Configure NPM
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      # Delete composer.lock
      - name: Delete composer.lock
        run: rm composer.lock

      # Install PHP dependencies
      - name: Install Composer dependencies
        run: composer require "illuminate/support:8.*" "illuminate/contracts:8.*"

      # Install NPM dependencies
      - name: Install Dependencies
        run: npm install

      # Build static assets
      - name: Compile Assets
        run: npm run prod

      # Run phpunit tests to generate coverage report
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: d7ac50851610b4bfae417c6942bba6a399435943951ee9c1fb470ad29c94f0ed
        with:
          coverageCommand: php -d pcov.enabled=1 ./vendor/bin/phpunit --coverage-clover=coverage.xml
          coverageLocations: |
            ${{github.workspace}}/coverage.xml:clover