name: Tests and coverage

on:
  push:
    branches:
      - '2.*'
  pull_request:
    types:
      - synchronize
      - opened
      - edited
      - reopened

jobs:
  compile-assets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      # Configure NPM
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      # Install NPM dependencies
      - name: Install Dependencies
        run: npm install

      # Build static assets
      - name: Compile Assets
        run: npm run prod

  run-tests:
    needs: compile-assets
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        laravel: [7.*]
        php: [7.2, 7.3, 7.4]
        experimental: [false]
        include:
        - laravel: 8.x-dev
          php: 8.0
          experimental: true
        - laravel: 7.*
          php: 8.0
          experimental: true

    steps:
      - uses: actions/checkout@master
      # Configure PHP
      - name: Select PHP version
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, pdo_sqlite, fileinfo, gd

      # Install PHP dependencies
      - name: Install Composer dependencies
        run: composer require "illuminate/support:${{ matrix.laravel }}"

      # Make sure the proper Chromedriver for Dusk is installed
      - name: Install Chromedriver for Dusk
        run: ./vendor/bin/dusk-updater detect --auto-update

      # Run tests
      - name: Run tests
        run: ./vendor/bin/phpunit --no-coverage